from django import forms

class ResumeForm(forms.Form):
    name = forms.CharField(max_length=100)
    contact_info = forms.CharField(max_length=255)
    email = forms.EmailField()
    phone = forms.CharField(max_length=15)
    skills = forms.CharField(max_length=255)
    degree = forms.CharField(max_length=100)
    university = forms.CharField(max_length=100)
    education_dates = forms.CharField(max_length=100)
    gpa = forms.CharField(max_length=10, required=False)
    job_title = forms.CharField(max_length=100)
    company_name = forms.CharField(max_length=100)
    job_location = forms.CharField(max_length=100)
    job_dates = forms.CharField(max_length=100)
    project_title = forms.CharField(max_length=100, required=False)
    project_description = forms.CharField(widget=forms.Textarea)
    certification_name = forms.CharField(max_length=100, required=False)
    certification_org = forms.CharField(max_length=100)
    certification_date = forms.CharField(max_length=50)
    award_name = forms.CharField(max_length=100, required=False)
    extracurricular = forms.CharField(max_length=100)
    extracurricular_description = forms.CharField(widget=forms.Textarea)
    profile_picture = forms.ImageField(required=False) 
