# Generated by Django 5.2 on 2025-05-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_name_resume_full_name_remove_resume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='generated_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
