# Generated by Django 5.2.1 on 2025-05-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_generated_content_resume_pdf_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
