# Generated by Django 5.2.1 on 2025-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0006_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('skills', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('education_dates', models.CharField(max_length=100)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_dates', models.CharField(max_length=100)),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField()),
                ('certification_name', models.CharField(blank=True, max_length=100, null=True)),
                ('certification_org', models.CharField(max_length=100)),
                ('certification_date', models.CharField(max_length=50)),
                ('award_name', models.CharField(blank=True, max_length=100, null=True)),
                ('extracurricular', models.CharField(max_length=100)),
                ('extracurricular_description', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
    ]
