# Generated by Django 5.2.1 on 2025-05-11 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='award_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='certification_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='certification_org',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_dates',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='extracurricular',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='extracurricular_description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_dates',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='university',
        ),
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
